package oeapi.controller;

import oeapi.controller.requestparameters.oeapiRequestParam;
import java.util.List;
import java.util.Map.Entry;
import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import jakarta.validation.Valid;

import oeapi.oeapiError;
import oeapi.oeapiException;
import oeapi.oeapiObjectsValidator;
import oeapi.oeapiUtils;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.BeanPropertyBindingResult;
import org.springframework.validation.Errors;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.ControllerAdvice;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.context.request.WebRequest;
import oeapi.service.oeapiServiceInterface;

/**
 *
 * @author itziar.urrutia
 */
@RestController
@ControllerAdvice
public class oeapiController<T> {

    Logger logger = LoggerFactory.getLogger(oeapiController.class);

    @Value("${ooapi.config.validationMode:true}")
    private boolean validationMode;

    @Autowired
    private oeapiObjectsValidator validator;

    protected ResponseEntity<?> NotFound(String id) {

        return ResponseEntity.notFound().build();

    }

    protected ResponseEntity<?> NotFound(String id, oeapiServiceInterface<T> service) {

        // Exception for offering and component. If not exist and varible then autogenerated and non persisted
        if (validationMode) {
            T obj = service.autoGenerateBasicItem(id);
            return ResponseEntity.ok(obj);
        } else {
            return this.NotFound(id);
        }
    }

    public void Validate(T object, Errors errors) {
        validator.validate(object, errors);
    }

    protected ResponseEntity<?> getResponse(List<?> items) {
        // Convert pageNumber (1-based index) to 0-based index for Pageable
        Pageable pageable = PageRequest.of(0, 10);
        oeapiResponse response = new oeapiResponse(items, pageable);
        return new ResponseEntity<>(response, HttpStatus.OK);

    }

    protected ResponseEntity<?> getResponse(Pageable pageable, List<?> items) {
        // Convert pageNumber (1-based index) to 0-based index for Pageable
        //            Pageable pageable = PageRequest.of(requestParam.getPageNumber() - 1, requestParam.getPageSize());

        oeapiResponse response = new oeapiResponse(items, pageable);
        return new ResponseEntity<>(response, HttpStatus.OK);

    }

    protected ResponseEntity<?> getResponse(Page<?> items) {
        // Convert pageNumber (1-based index) to 0-based index for Pageable
        //            Pageable pageable = PageRequest.of(requestParam.getPageNumber() - 1, requestParam.getPageSize());

        oeapiResponse response = new oeapiResponse(items);
        return new ResponseEntity<>(response, HttpStatus.OK);

    }

    protected ResponseEntity<?> getAll(Pageable pageable, oeapiServiceInterface<T> service) {

        Page<T> pages = service.getAll(pageable);

        return this.getResponse(pages);

    }

    public ResponseEntity<?> getAll(Entry<String, String> filter, Pageable pageable, oeapiServiceInterface<T> service) {

        if (filter == null) {
            return this.getAll(pageable, service);
        }

        if (filter.getKey().equals("primaryCode")) {
            return this.getAllByPrimaryCode(filter.getValue(), pageable, service);
        } else {
            return this.getAllByFieldValue(filter.getKey(), filter.getValue(), pageable, service);
        }

    }

    protected ResponseEntity<?> getAllByPrimaryCode(String primaryCode, Pageable pageable, oeapiServiceInterface<T> service) {

        Page<T> pages = service.getByPrimaryCode(primaryCode, pageable);

        return this.getResponse(pages);
    }

    protected ResponseEntity<?> getAllByPrimaryCode(String primaryCode, oeapiRequestParam requestParam, oeapiServiceInterface<T> service) {

        Pageable pageable = PageRequest.of(0, 100);
        return this.getAllByPrimaryCode(primaryCode, pageable, service);

    }

    protected ResponseEntity<?> getAllByFieldValue(String field, String value, oeapiRequestParam requestParam, oeapiServiceInterface<T> service) {

        Pageable pageable = PageRequest.of(0, 100);
        return this.getAllByFieldValue(field, value, pageable, service);

    }

    public ResponseEntity<?> getAllByFieldValue(String field, String value, Pageable pageable, oeapiServiceInterface<T> service) {

        Page<T> pages = service.getByField(field, value, pageable);

        return this.getResponse(pages);

    }

    public ResponseEntity<?> get(String id, oeapiServiceInterface<T> service) {
        Optional<T> p = service.getById(id);
        if (!p.isPresent()) {
            return ResponseEntity.badRequest().body("Error: " + id + " not found");
        } else {
            T obj = p.get();

            return ResponseEntity.ok(obj);
        }

    }

    public ResponseEntity<?> update(@RequestBody @Valid T requestBody, oeapiServiceInterface<T> service) {

        ResponseEntity finalResponse = null;
        Errors errors = new BeanPropertyBindingResult(requestBody, requestBody.getClass().getName().toLowerCase());
        T updated;

        // Just for debugging, see how the parsed JSON looks like
        logger.debug("ooapiController (super): Entering Update with this JSON: " + requestBody);

        logger.debug("ooapiController (super): Going to validate...");
        this.Validate(requestBody, errors);

        if (errors.hasErrors()) {
            throw new oeapiException(HttpStatus.BAD_REQUEST, "Error JSON validation", errors.getAllErrors().toString());  // TDB Fine tune status
        }

        try {
            logger.debug("ooapiController (super): Validated and ready to call service to update BD");
            updated = service.update(requestBody);
            finalResponse = ResponseEntity.ok(updated);
        } catch (oeapiException ooapiEx) {
            logger.error("ooapiController (super): " + ooapiEx.getTitle());
            throw new oeapiException(HttpStatus.NOT_FOUND, ooapiEx.getTitle(), ooapiEx.getDetail());  // TDB Fine tune status
        } catch (Exception ex) {
            logger.error("ooapiController (super): " + ex);
            throw new oeapiException(HttpStatus.INTERNAL_SERVER_ERROR, "Not handled Exception", ex.getLocalizedMessage());   // TDB Fine tune status
        }

        logger.debug("ooapiController (super): BD Updated");

        return finalResponse;
    }

    public ResponseEntity<?> create(@RequestBody @Valid T requestBody, oeapiServiceInterface<T> service) {

        ResponseEntity<T> finalResponse = null;
        Errors errors = new BeanPropertyBindingResult(requestBody, requestBody.getClass().getName().toLowerCase());
        T created;
        //validator.validate(program,errors)
        // Just for debugging, see how the parsed JSON looks like
        logger.debug("ooapiController create, requestBody: " + oeapiUtils.debugJSON(requestBody));

        this.Validate(requestBody, errors);
        if (errors.hasErrors()) {
            throw new oeapiException(HttpStatus.BAD_REQUEST, "Error JSON validation", errors.getAllErrors().toString());  // TDB Fine tune status
        }
        try {
            created = service.create(requestBody);
            finalResponse = ResponseEntity.ok(created);
        } catch (oeapiException ooapiEx) {
            logger.error("ooapiController create: ooapiException " + ooapiEx.getTitle());
            throw new oeapiException(ooapiEx.getStatus(), ooapiEx.getTitle(), ooapiEx.getDetail());  // TDB Fine tune status
        } catch (Exception ex) {
            logger.error("ooapiController create: Exception  " + ex);
            throw new oeapiException(HttpStatus.INTERNAL_SERVER_ERROR, "Not handled Exception", ex.getLocalizedMessage());   // TDB Fine tune status
        }
        return finalResponse;
    }

    public ResponseEntity<String> createByJSON(List<T> items, oeapiServiceInterface<T> service) {

        /* Check if this entry point allows updates using REST or is it read-only
        if (!allowRestToModify) {
            throw new oeapiException(HttpStatus.NOT_FOUND, "This OOAPI entry point does not allow updates using REST");
        }
         */
        ResponseEntity itemResponse;
        StringBuilder textResult = new StringBuilder();

        int countProcessed = 0;
        int countWithError = 0;

        for (T item : items) {
            itemResponse = this.create(item, service);
            textResult.append("\n" + itemResponse.getBody());

            countProcessed++;

            if (itemResponse.getStatusCodeValue() > 299) {
                countWithError++;
            }
        }

        textResult.insert(0, "Objects processed: " + countProcessed + ", Courses with error: " + countWithError + ", Full log: ");

        return new ResponseEntity<>(textResult.toString(), HttpStatus.ACCEPTED);

    }

    @ExceptionHandler(oeapiException.class)
    public ResponseEntity<oeapiError> handleOoapiUnitaException(oeapiException ex, WebRequest request) {

        oeapiError error = new oeapiError(ex.getStatus().name(), ex.getTitle());

        return ResponseEntity.status(HttpStatus.NOT_FOUND)
                .contentType(MediaType.APPLICATION_PROBLEM_JSON)
                .body(error);
    }
}
