## YAML Template.
---
type: object
properties:
  primaryCode:
    type: object
    properties:
      codeType:
        type: string
        enum: ["identifier", "otherType"] # Enumerated values
      code:
        type: string
    required: ["codeType", "code"]
  name:
    type: array
    items:
      type: object
      properties:
        language:
          type: string
        value:
          type: string
      required: ["language", "value"]
  programId:
    type: string
    format: uuid # Validate UUID format
required: ["primaryCode", "name", "programId"]