package oeapi.service;

import java.util.List;

import java.util.Optional;
import java.util.UUID;

import javax.transaction.Transactional;
import oeapi.model.AcademicSession;
import oeapi.oeapiUtils;
import oeapi.repository.AcademicSessionRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
 *
 * @author itziar.urrutia
 */
@Service
@Transactional
public class AcademicSessionService extends oeapiEndpointService<AcademicSession, AcademicSessionRepository> {

    public Page<AcademicSession> getChildren(String parentId, Pageable pageable) {
        return this.getByField("parent", parentId, pageable);
    }

    public AcademicSessionService() {
        super();
    }

    @Override
    public AcademicSession update(AcademicSession o) {
        return super.create(o);
    }

    @Override
    public AcademicSession autoGenerateBasicItem(String id) {
        AcademicSession academicSession = new AcademicSession();
        academicSession.setAcademicSessionId(id);
        academicSession.setName(oeapiUtils.defaultName());
        return academicSession;
    }

    @Override
    public AcademicSession autoGenerateBasicItem() {
        return this.autoGenerateBasicItem(UUID.randomUUID().toString() + "-Autogenerated-AcademicSession");
    }

}
