package oeapi.service;

import java.util.List;
import java.util.Optional;
import java.util.UUID;

import javax.transaction.Transactional;
import oeapi.model.Association;
import oeapi.model.Result;
import oeapi.repository.AssociationRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
 *
 * @author itziar.urrutia
 */
@Service
@Transactional
public class AssociationService extends oeapiEndpointService<Association, AssociationRepository> implements oeapiServiceInterface<Association> {

    public AssociationService() {
        super();
    }

    @Override
    public Association create(Association o) {
        return super.create(o);
    }

    @Override
    public Optional<Association> getById(String id) {
        return repository.findById(id);
    }

    @Override
    public Page<Association> getByField(String field, String value, Pageable pageable) {
        String capitalizedMethodName = "findBy" + field.substring(0, 1).toUpperCase() + field.substring(1);
        return super.findByDynamicMethod(capitalizedMethodName, value, pageable);
    }

    @Override
    public Page<Association> getByPrimaryCode(String code, Pageable pageable) {

        return super.getByPrimaryCode(code, pageable);
    }

    @Override
    public Page<Association> getAll(Pageable pageable) {
        return super.getAll(pageable);
    }

    @Override
    public List<Association> getAll() {
        return super.getAll();
    }

    @Override
    public Association autoGenerateBasicItem(String id) {
        Association association = new Association();
        association.setAssociationId(id);

        association.setAssociationType("courseOfferingAssociation");
        association.setAssociationRole("student");
        association.setRemoteState("pending");
        Result aResult = new Result();
        aResult.setResultState("completed");
        aResult.setPass("passed");
        aResult.setComment("result");
        aResult.setScore("9");
        aResult.setWeight(100);
        association.setResult(aResult);

        return association;
    }

    @Override
    public Association autoGenerateBasicItem() {
        return this.autoGenerateBasicItem(UUID.randomUUID().toString() + "-Autogenerated");
    }

}
