package oeapi.service;

import java.util.List;

import java.util.Optional;
import java.util.UUID;

import jakarta.transaction.Transactional;
import oeapi.model.Address;
import oeapi.model.Building;
import oeapi.oeapiUtils;
import oeapi.repository.BuildingRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
 *
 * @author itziar.urrutia
 */
@Service
@Transactional
//public class BuildingService extends oeapiEndpointService<Building, BuildingRepository> implements ooapiService<Building> {
public class BuildingService extends oeapiEndpointService<Building, BuildingRepository> {

    public BuildingService() {
        super();
    }

    @Override
    public Building autoGenerateBasicItem(String id) {
        Building building = new Building();
        building.setBuildingId(id);
        String defaultAbbr = "Autogenerated Abbreviation for Id: " + id;
        building.setName(oeapiUtils.defaultName());
        building.setDescription(oeapiUtils.defaultDescription());
        building.setAbbreviation(defaultAbbr);

        Address address = new Address();

        //ToDo - Add detail in address
        building.setAddress(address);

        return building;
    }

    @Override
    public Building autoGenerateBasicItem() {
        return this.autoGenerateBasicItem(UUID.randomUUID().toString() + "-Autogenerated Building");
    }

}
