package oeapi.service;

import java.util.List;

import java.util.Optional;
import java.util.UUID;

import javax.transaction.Transactional;
import oeapi.model.EducationSpecification;
import oeapi.oeapiUtils;
import oeapi.repository.EducationSpecificationRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
 *
 * @author itziar.urrutia
 */
@Service
@Transactional
public class EducationSpecificationService extends oeapiEndpointService<EducationSpecification, EducationSpecificationRepository> implements oeapiServiceInterface<EducationSpecification> {

    public EducationSpecificationService() {
        super();
    }

    public List<EducationSpecification> getByOrganizationId(String id) {

        return repository.findByOrganization_OrganizationId(id);
    }

    @Override
    public EducationSpecification autoGenerateBasicItem(String id) {
        EducationSpecification educationSpecification = new EducationSpecification();
        educationSpecification.setEducationSpecificationId(id);
        educationSpecification.setName(oeapiUtils.defaultName());
        educationSpecification.setDescription(oeapiUtils.defaultDescription());
        educationSpecification.setAbbreviation("Autogenerated EduSpec for Id: " + id);
        educationSpecification.setPrimaryCode(oeapiUtils.defaultPrimaryCode("identifier", id + "-AutoGenerated"));
        educationSpecification.setEducationSpecificationType("course");

        return educationSpecification;
    }

    @Override
    public EducationSpecification autoGenerateBasicItem() {
        return this.autoGenerateBasicItem(UUID.randomUUID().toString() + "-Autogenerated-EducationSpecification");
    }

}
