package oeapi.service;

import java.util.List;

import java.util.Optional;
import java.util.UUID;

import jakarta.transaction.Transactional;
import oeapi.model.EducationSpecification;
import oeapi.model.Group;
import oeapi.oeapiUtils;
import oeapi.repository.GroupRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
 *
 * @author itziar.urrutia
 */
@Service
@Transactional
public class GroupService extends oeapiEndpointService<Group, GroupRepository> implements oeapiServiceInterface<Group> {

    public List<Group> getPersonsByPersonId(String id) {

        return repository.findByMembers_PersonId(id);
    }

    public List<Group> getByOrganizationId(String id) {

        return repository.findByOrganization_OrganizationId(id);

    }

    @Override
    public Group autoGenerateBasicItem(String id) {
        Group group = new Group();
        group.setGroupId(id);
        group.setName(oeapiUtils.defaultName());
        group.setDescription(oeapiUtils.defaultDescription());
        group.setAbbreviation("Autogenerated Group for Id: " + id);
        group.setPrimaryCode(oeapiUtils.defaultPrimaryCode("identifier", id + "-AutoGenerated"));
        group.setGroupType("class");

        return group;
    }

    @Override
    public Group autoGenerateBasicItem() {
        return this.autoGenerateBasicItem(UUID.randomUUID().toString() + "-Autogenerated-Group");
    }
}
