package oeapi.service;

import java.util.List;

import java.util.Optional;
import java.util.UUID;

import javax.transaction.Transactional;
import oeapi.oeapiUtils;
import oeapi.model.NewsFeed;
import oeapi.repository.NewsFeedRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
 *
 * @author itziar.urrutia
 */
@Service
@Transactional
public class NewsFeedService extends oeapiEndpointService<NewsFeed, NewsFeedRepository> implements oeapiServiceInterface<NewsFeed> {

    public NewsFeedService() {
        super();
    }

    @Override
    public NewsFeed autoGenerateBasicItem(String id) {
        NewsFeed newsFeed = new NewsFeed();
        newsFeed.setNewsFeedId(id);
        newsFeed.setName(oeapiUtils.defaultName());

        newsFeed.setPrimaryCode(oeapiUtils.defaultPrimaryCode("identifier", id + "-AutoGenerated"));
        newsFeed.setNewsFeedType("course");
        return newsFeed;
    }

    @Override
    public NewsFeed autoGenerateBasicItem() {
        return this.autoGenerateBasicItem(UUID.randomUUID().toString() + "-Autogenerated-NewsFeed");
    }

}
