package oeapi.service;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import java.util.logging.Level;
import javax.transaction.Transactional;
import oeapi.model.Organization;
import oeapi.model.Person;
import oeapi.oeapiException;
import oeapi.oeapiUtils;

import oeapi.repository.PersonRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;

/**
 *
 * @author itziar.urrutia
 */
@Service
@Transactional
public class PersonService extends oeapiEndpointService<Person, PersonRepository> {

    Logger logger = LoggerFactory.getLogger(PersonService.class);

    @Value("${ooapi.config.autoCreateCoordinatorIfNotExists:false}")
    private boolean autoCreateIfNotExists;

    public List<Person> createRelated(List<Person> relatedList) {
        List<Person> createRelated = new ArrayList<>();
        relatedList.forEach(p -> {
            List<Person> pList = this.getObjectByPrimaryCode(p.getPrimaryCode().getCode());
            if (pList.isEmpty()) {
                createRelated.add(this.create(p));
            } else {
                createRelated.add(pList.get(0));
            }
        }
        );
        return createRelated;

    }
    
    @Override
    public List<Person> manageRelated(List<Person> relateList) throws Exception  {
            return this.manageRelated(relateList, autoCreateIfNotExists);  
    }
    
    @Override
    public List<Person> manageRelated(List<Person> relateList, boolean autoCreateIfNotExists) throws Exception {
        //return super.manageRelated(relateList);

        logger.debug("manageRelated: Revising person/coord supplied IDs. AutoCreateIfNotExists is: "+autoCreateIfNotExists);
        List<Person> newRelateList = new ArrayList<>();

        for (Person relate : relateList) {
            String id = oeapiUtils.getId(relate).toString();
            logger.debug("manageRelated examining Person Id: "+id);
            Optional<Person> relExisting = manageRelated(id);

            if (relExisting.isPresent()) {
                logger.debug("manageRelated found Id. Then add Id: "+id+" to owner object");                
                newRelateList.add(relExisting.get());
             } else
                if (autoCreateIfNotExists) {
                    logger.debug("manageRelated has NOT FOUND Id. "+id+" +++ autocreating one based on ID");                
                    newRelateList.add(this.autoGenerateBasicItem(id));                    
                } else {
                    logger.debug("manageRelated has NOT FOUND Id. "+id+" and autocreate is FALSE");                
                    throw new oeapiException(HttpStatus.BAD_REQUEST, "Check person/coordinatos related list", "Element [" + id + "] not found");
                }
        }        

        return newRelateList;
        
    }    

    @Override
    public Person autoGenerateBasicItem(String personId) {

        Person person = new Person(personId);
        person.setPrimaryCode(oeapiUtils.defaultPrimaryCode("identifier", "AutoGen-Person-For-Id-" + personId));
        person.setSurname("AutoGen Surname-" + personId);
        person.setGivenName("AutoGen Givename-" + personId);
        person.setDisplayName("AutoGen employee-" + personId);
        person.setActiveEnrollment(false);
        List<String> affiliations = new ArrayList<>();
        affiliations.add("employee");
        person.setAffiliations(affiliations);
        person.setMail("AutoGen.employee." + personId + "@unita.eu");

        return person;
    }

    @Override
    public Person autoGenerateBasicItem() {

        return this.autoGenerateBasicItem(UUID.randomUUID().toString() + "-Autogenerated-Person");
    }
}
