package oeapi.service;

import java.util.List;

import java.util.Optional;
import java.util.UUID;

import jakarta.transaction.Transactional;
import oeapi.model.Room;
import oeapi.oeapiUtils;
import oeapi.repository.RoomRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

/**
 *
 * @author itziar.urrutia
 */
@Service
@Transactional
public class RoomService extends oeapiEndpointService<Room, RoomRepository> {

    public List<Room> getByBuildingId(String id) {
        return repository.findByBuilding_BuildingId(id);
    }

    @Override
    public Room autoGenerateBasicItem(String id) {
        Room room = new Room();
        room.setRoomId(id);
        room.setName(oeapiUtils.defaultName());
        room.setDescription(oeapiUtils.defaultDescription());
        room.setAbbreviation("Autogenerated Room for Id: " + id);
        room.setPrimaryCode(oeapiUtils.defaultPrimaryCode("identifier", id + "-AutoGenerated"));
        room.setRoomType("general purpose");

        return room;
    }

    @Override
    public Room autoGenerateBasicItem() {
        return this.autoGenerateBasicItem(UUID.randomUUID().toString() + "-Autogenerated-Group");
    }

}
