name: Check deps for vulnerabilities

on:
  workflow_call:
    secrets:
      NVD_API_TOKEN:
        required: true
  push:
    branches: ["*"]
  schedule:
    - cron: '0 1 * * 1,2,3,4,5' # every workday

jobs:
  deps:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '18'

    - uses: actions/checkout@v6

    - name: Cache maven repository
      uses: actions/cache@v5
      with:
        path: "~/.m2"
        key: "${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}"
        restore-keys: |
          ${{ runner.os }}-m2

    - id: get-dates
      shell: bash
      run: |
        echo "today=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        echo "yesterday=$(/bin/date -u "+%Y%m%d" --date=yesterday)" >> $GITHUB_OUTPUT
        echo "two_days_ago=$(/bin/date -u "+%Y%m%d" --date='2 days ago')" >> $GITHUB_OUTPUT
        echo "three_days_ago=$(/bin/date -u "+%Y%m%d" --date='3 days ago')" >> $GITHUB_OUTPUT

    - name: Restore NVD database
      id: nvd-database-restore
      uses: actions/cache/restore@v5
      with:
        path: "~/.m2/repository/org/owasp/dependency-check-data"
        key: "${{ runner.os }}-nvd-${{ steps.get-dates.outputs.today }}"
        restore-keys: |
          ${{ runner.os }}-nvd-${{ steps.get-dates.outputs.yesterday }}
          ${{ runner.os }}-nvd-${{ steps.get-dates.outputs.two_days_ago }}
          ${{ runner.os }}-nvd-${{ steps.get-dates.outputs.three_days_ago }}
          ${{ runner.os }}-nvd

    - env:
        NVD_API_TOKEN: ${{ secrets.NVD_API_TOKEN }}
      if: ${{ env.NVD_API_TOKEN == '' }}
      run: echo "NVD_API_TOKEN secret is empty"; exit 1

    - name: run dependency-check
      env:
        NVD_API_TOKEN: ${{ secrets.NVD_API_TOKEN }}
      run: |
        mvn org.owasp:dependency-check-maven:check -DfailBuildOnCVSS=8

    - name: Save NVD database
      id: nvd-database-save
      if: always() && steps.nvd-database-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v5
      with:
        path: "~/.m2/repository/org/owasp/dependency-check-data"
        key: "${{ runner.os }}-nvd-${{ steps.get-dates.outputs.today }}"
