name: Build and Push Container Image

on:
  push:
    tags: ["v*"]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  nvd:
    uses: ./.github/workflows/nvd.yml
    secrets:
       NVD_API_TOKEN: ${{ secrets.NVD_API_TOKEN }}

  build-and-push:
    needs: [test, nvd]

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Required to publish to GHCR

    steps:
    - name: Install Cosign
      uses: sigstore/cosign-installer@v4.1.2

    - name: Checkout code
      uses: actions/checkout@v6

    - name: Log in to SURF CR
      uses: docker/login-action@v3
      with:
        registry: cr.surf.nl
        username: ${{ secrets.HARBOR_USERNAME }}
        password: ${{ secrets.HARBOR_PASSWORD }}

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels)
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/${{ github.repository }}
          cr.surf.nl/oeapi-endpoint-quickstart/oeapi-endpoint-quickstart
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Build and push container image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Sign image with a key
      run: |
        images=""
        for tag in ${TAGS}; do
          cosign sign --yes --key env://COSIGN_PRIVATE_KEY ${tag}@${DIGEST} --new-bundle-format=false --use-signing-config=false
        done
      env:
        TAGS: ${{ steps.meta.outputs.tags }}
        COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_KEY }}
        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
        DIGEST: ${{ steps.build-and-push.outputs.digest }}