name: Run tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - db_image: 'mysql'
            db_health_cmd: 'mysqladmin ping -h localhost -u root -px'
            db_root_pw_var: 'MYSQL_ROOT_PASSWORD'
            db_database_var: 'MYSQL_DATABASE'
            db_user_var: 'MYSQL_USER'
            db_password_var: 'MYSQL_PASSWORD'
            datasource_driver_class: 'com.mysql.cj.jdbc.Driver'
            datasource_url: 'jdbc:mysql://localhost/oeapi_qs'
          - db_image: 'mariadb'
            db_health_cmd: 'healthcheck.sh --connect --innodb_initialized'
            db_root_pw_var: 'MARIADB_ROOT_PASSWORD'
            db_database_var: 'MARIADB_DATABASE'
            db_user_var: 'MARIADB_USER'
            db_password_var: 'MARIADB_PASSWORD'
            datasource_driver_class: 'org.mariadb.jdbc.Driver'
            datasource_url: 'jdbc:mariadb://localhost/oeapi_qs'

    services:
      database:
        image: ${{ matrix.db_image }}
        env:
          ${{ matrix.db_root_pw_var }}: x
          ${{ matrix.db_database_var }}: oeapi_qs
          ${{ matrix.db_user_var }}: oeapi_qs
          ${{ matrix.db_password_var }}: oeapi_qs
        ports:
          - 3306:3306
        options: >-
          --health-cmd="${{ matrix.db_health_cmd }}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:

    - uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '18'

    - uses: actions/checkout@v6

    - uses: actions/cache@v5
      with:
        path: "~/.m2"
        key: "${{ runner.os }}-m2-${{ hashFiles('pom.xml') }}"
        restore-keys: |
          ${{ runner.os }}-m2

    - name: run tests
      env:
        SPRING_DATASOURCE_DRIVER_CLASS_NAME: ${{ matrix.db_driver_class_name }}
        SPRING_DATASOURCE_URL: ${{ matrix.datasource_url }}
      run: |
        mvn -DskipTests=false clean test
